#!/usr/bin/env python
# -*- mode: python -*-
import sys
import os

if len(sys.argv) < 3:
    sys.exit('Usage: gravel node {nodegroup} {action}')

action = 'node-' + sys.argv[2]

if action not in os.listdir('operator.d'):
    sys.exit('unknown action %s' % action)

args = ['operator.d/' + action, sys.argv[1]] + sys.argv[3:]

os.execv(args[0], args)
